# Generated by Django 6.0.1 on 2026-02-12 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Disaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "disaster_type",
                    models.CharField(
                        choices=[
                            ("fire", "Fire"),
                            ("earthquake", "Earthquake"),
                            ("flood", "Flood"),
                        ],
                        max_length=20,
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("latitude", models.FloatField(null=True)),
                ("longitude", models.FloatField(null=True)),
                ("severity_score", models.FloatField(default=0)),
                ("confidence_score", models.FloatField(default=0)),
                ("population_affected", models.IntegerField(default=0)),
                ("priority_score", models.FloatField(default=0)),
                ("status", models.CharField(default="reported", max_length=20)),
                ("reported_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-priority_score", "-reported_at"],
            },
        ),
        migrations.CreateModel(
            name="FireStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=255)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("available_trucks", models.IntegerField(default=3)),
                ("operational", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Hospital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("available_ambulances", models.IntegerField(default=5)),
                ("operational", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="DispatchDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dispatch_type",
                    models.CharField(
                        choices=[("fire", "Fire Truck"), ("ambulance", "Ambulance")],
                        max_length=20,
                    ),
                ),
                ("distance_km", models.FloatField()),
                ("estimated_arrival_minutes", models.FloatField()),
                ("route_data", models.JSONField()),
                ("dispatched_at", models.DateTimeField(auto_now_add=True)),
                (
                    "disaster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispatches",
                        to="api.disaster",
                    ),
                ),
                (
                    "fire_station",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.firestation",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.hospital",
                    ),
                ),
            ],
        ),
    ]
