# Generated by Django 6.0.2 on 2026-03-06 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disaster',
            name='resolution_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='disaster',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
