# Generated by Django 6.0.2 on 2026-04-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_disaster_analysis_and_escalation_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disaster',
            name='disaster_type',
            field=models.CharField(choices=[('fire', 'Fire'), ('earthquake', 'Earthquake'), ('flood', 'Flood'), ('chemical', 'Chemical'), ('medical', 'Medical'), ('traffic', 'Traffic Accident')], max_length=20),
        ),
    ]
